version: '3'

volumes:
  data_test: {}

services:
  djcorecap:
    build:
      context: .
      dockerfile: ./compose/djcorecap/Dockerfile
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    image: djcorecap:test
    volumes:
      - .:/djcorecap
      - data_test:/data
